name: Download Volume Backup

on: 
  workflow_dispatch:
    inputs:
      serverName:
        description: 'Server name'
        type: string
        required: true
      backupFile:
        description: 'Backup file name'
        type: string
        required: true

jobs:
  download:
    name: Download Backup
    runs-on: ubuntu-latest
    steps:
      - name: Check file and download
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ inputs.serverName }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          script: |
            # Check if file exists
            if [ ! -f ~/${{ inputs.backupFile }} ]; then
              echo "File ~/${{ inputs.backupFile }} not found!"
              exit 1
            fi

      - name: Download backup file
        run: |
          # Create SSH key file
          echo "${{ secrets.DOCKER_SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
          
          # Download the file using scp
          scp -i ssh_key -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ inputs.serverName }}:~/${{ inputs.backupFile }} .
          
          # Clean up the key file
          rm ssh_key

      - name: Upload backup as artifact
        uses: actions/upload-artifact@v4
        with:
          name: volume-backup
          path: ${{ inputs.backupFile }}
          retention-days: 5 