name: Volume Backup

on: 
  workflow_call:
    inputs:
      serverName:
        type: string
        required: true
      volumeName:
        type: string
        required: true
      volumePath:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      serverName:
        description: 'Server name'
        type: string
        required: true
      volumeName:
        description: 'Docker volume name'
        type: string
        required: true
      volumePath:
        description: 'Volume mount path inside container'
        type: string
        required: true

jobs:
  backup:
    name: Backup Volume
    runs-on: ubuntu-latest
    env:
      BACKUP_FILE: ${{ inputs.volumeName }}-backup-${{ github.run_id }}.tar
    steps:
      - name: Create backup
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ inputs.serverName }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          envs: BACKUP_FILE
          script: |
            # Create the backup using docker
            docker run --rm \
              -v ${{ inputs.volumeName }}:${{ inputs.volumePath }} \
              -v $(pwd):/backup \
              busybox:1.37.0 \
              sh -c "cd ${{ inputs.volumePath }} && tar cf /backup/${BACKUP_FILE} .";

      - name: Download backup file
        run: |
          # Create SSH key file
          echo "${{ secrets.DOCKER_SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
          
          # Download the file using scp
          scp -i ssh_key -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ inputs.serverName }}:~/${{ env.BACKUP_FILE }} .
          
          # Clean up the key file
          rm ssh_key

      - name: Upload backup as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BACKUP_FILE }}
          path: ${{ env.BACKUP_FILE }}
          retention-days: 1

      - name: Remove backup from server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ inputs.serverName }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          envs: BACKUP_FILE
          script: |
            rm ${BACKUP_FILE}